version: '3.8'

services:
  rfq-process-mining:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: rfq-mtl-m-monitoring
    image: rfq-process-mining:latest
    ports:
      - "8888:8888"  # Jupyter Lab
    volumes:
      - ../traces:/app/rfq_process_mining/traces
      - ../monitoring:/app/rfq_process_mining/monitoring
      - ../results:/app/rfq_process_mining/results
      - ../specifications:/app/rfq_process_mining/specifications
      - rfq_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - rfq-network

  # Optional: Add a web interface for viewing results
  rfq-web-viewer:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    container_name: rfq-web-viewer
    image: rfq-web-viewer:latest
    ports:
      - "3000:3000"  # Web interface
    volumes:
      - ../results:/app/results:ro
    environment:
      - NODE_ENV=production
    depends_on:
      - rfq-process-mining
    networks:
      - rfq-network
    profiles:
      - web

volumes:
  rfq_data:
    driver: local

networks:
  rfq-network:
    driver: bridge

